//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Imfarsa.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Id_Tarea { get; set; }
        public string Descripcion { get; set; }
        public int Id_Estado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Estado { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public int Id_Prioridad { get; set; }
    
        public virtual Estado_Tarea Estado_Tarea { get; set; }
        public virtual Prioridad Prioridad { get; set; }
    }
}
